### PR TITLE
Add ELECTRON_MIRROR

### PR DESCRIPTION
**Pull request by popomore**
https://github.com/maxogden/electron-download/pull/2

### CODE REVIEW

**Comment by popomore** [comment]
https://github.com/atom/electron#downloads

https://github.com/mafintosh/electron-prebuilt/blob/master/package.json#L20

**Comment by fengmk2** [comment]
+1

**Comment by popomore** [comment]
https://github.com/maxogden/electron-download/pull/3

**Comment by popomore** [comment]
0.10 挂了，好像跟这次修改无关

**Comment by fengmk2** [comment]
+1

**Comment by fengmk2** [comment]
tnpm 也提交一个？

**Comment by fengmk2** [comment]
cnpm@3.0.2

**Comment by popomore** [comment]
tnpm 已经发了

**Pull request merged**
