### PR TITLE
feat: [BREAKING_CHANGE] use npminstall@3 and npm@5

### PR DESCRIPTION
**Pull request by fengmk2**
and move all *.js to lib

---
This change is [Reviewable](https://reviewable.io/reviews/cnpm/cnpm/187)

### CODE REVIEW

**Comment by fengmk2** [comment]
https://github.com/npm/npm/releases/tag/v4.5.0  Add support for filtered package metadata

**Comment by fengmk2** [comment]
https://github.com/cnpm/npminstall/pull/221

**Comment by erbrother** [comment]
使用 cnpm install cnpm@beta -g 会报错：
  Error: EPERM: operation not permitted, open 'C:\Users\Administrator\AppData\Roaming\npm\cnpm'
    at Error (native)
要使用 npm install cnpm@beta -g才行

**Comment by fengmk2** [comment]
@erbrother 你再试试 `cnpm install cnpm@beta -g` ?

**Comment by fengmk2** [comment]
5.0.0

**Pull request merged**
